version: '3.7'
services:
  sbt:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /code
    command:
    - "sleep"
    - "36000"
